# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Reference')),
                ('web_pricing', models.BooleanField(default=False)),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=64, verbose_name='Customer')),
                ('create_date', models.DateTimeField()),
                ('supplier_info_state', models.CharField(choices=[('draft', 'Not Started'), ('rfq', 'Awaiting Upload'), ('complete', 'Complete')], default='draft', max_length=16, verbose_name='Supplier Information State')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Parent Product')),
                ('description', models.TextField(verbose_name='Description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProductComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=64, verbose_name='MPN')),
                ('manufacturer', models.CharField(max_length=64, verbose_name='Manufacturer')),
                ('uom_id', models.IntegerField(verbose_name='Unit Of Measure ID')),
                ('qty', models.FloatField(verbose_name='Quantity')),
                ('description', models.TextField(verbose_name='Description')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.ProjectProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProductQuoteQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('project_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.ProjectProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Project')),
            ],
        ),
    ]
