# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=64, verbose_name='MPN')),
                ('manufacturer', models.CharField(max_length=64, verbose_name='Manufacturer')),
                ('uom_id', models.IntegerField(verbose_name='Unit Of Measure ID')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Parent Product')),
                ('description', models.TextField(verbose_name='Description')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='ParentComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Component')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(max_length=64, null=True)),
                ('mpn', models.CharField(max_length=64, null=True)),
                ('uom_id', models.IntegerField()),
                ('moq', models.FloatField()),
                ('order_multiples', models.FloatField()),
                ('current_stock', models.FloatField()),
                ('leadtime', models.IntegerField()),
                ('sequence', models.IntegerField(default=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Component')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProductQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.SupplierComponent')),
                ('quote_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.QuoteQuantity')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectproduct',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectproductcomponent',
            name='project_product',
        ),
        migrations.RemoveField(
            model_name='projectproductquotequantity',
            name='project_product',
        ),
        migrations.AddField(
            model_name='projectsupplier',
            name='supplier_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsupplier',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('draft', 'Not Started'), ('complete', 'Complete'), ('rfq', 'Awaiting Upload')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
        migrations.DeleteModel(
            name='ProjectProduct',
        ),
        migrations.DeleteModel(
            name='ProjectProductComponent',
        ),
        migrations.DeleteModel(
            name='ProjectProductQuoteQuantity',
        ),
        migrations.AddField(
            model_name='suppliercomponent',
            name='project_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.ProjectSupplier'),
        ),
        migrations.AddField(
            model_name='quotequantity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Project'),
        ),
        migrations.AddField(
            model_name='parent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Project'),
        ),
        migrations.AddField(
            model_name='component',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Project'),
        ),
    ]
