# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0003_auto_20180223_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('draft', 'Not Started'), ('complete', 'Complete'), ('rfq', 'Awaiting Upload')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
    ]
