# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0004_auto_20180226_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='msl',
            field=models.IntegerField(blank=True, null=True, verbose_name='Moisture Sensitivity Level'),
        ),
        migrations.AddField(
            model_name='component',
            name='product_code',
            field=models.CharField(max_length=200, null=True, verbose_name='Product Code'),
        ),
        migrations.AddField(
            model_name='component',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('draft', 'Not Started'), ('complete', 'Quoted'), ('uploaded', 'Uploaded'), ('rfq', 'Awaiting Upload')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsupplier',
            unique_together=set([('project', 'supplier_id')]),
        ),
    ]
