# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0005_auto_20180305_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercomponent',
            name='alternative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliercomponent',
            name='state',
            field=models.CharField(choices=[('reject', 'Rejected'), ('pending', 'Pending'), ('normal', 'Accepted')], default='normal', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('draft', 'Not Started'), ('uploaded', 'Uploaded'), ('rfq', 'Awaiting Upload'), ('complete', 'Quoted')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
        migrations.AlterField(
            model_name='suppliercomponent',
            name='current_stock',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='suppliercomponent',
            name='leadtime',
            field=models.IntegerField(null=True),
        ),
    ]
