# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0006_auto_20180306_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsupplier',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('rfq', 'Awaiting Upload'), ('complete', 'Quoted'), ('draft', 'Not Started'), ('uploaded', 'Uploaded')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
        migrations.AlterField(
            model_name='suppliercomponent',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('normal', 'Accepted'), ('reject', 'Rejected')], default='normal', max_length=16, verbose_name='State'),
        ),
    ]
