# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0008_auto_20180312_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomChildParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('uom_id', models.IntegerField()),
                ('uom_name', models.CharField(max_length=16)),
                ('bom_type', models.CharField(choices=[('phantom', 'phantom'), ('normal', 'normal')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='BomComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('uom_id', models.IntegerField()),
                ('uom_name', models.CharField(max_length=16)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Component')),
            ],
        ),
        migrations.CreateModel(
            name='BomParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('quantity', models.FloatField()),
                ('uom_id', models.IntegerField()),
                ('uom_name', models.CharField(max_length=16)),
                ('routing_name', models.CharField(max_length=16)),
                ('routing_id', models.IntegerField()),
                ('procure_method', models.CharField(choices=[('make_to_order', 'Make to Order'), ('make_to_stock', 'Make to Stock')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Designator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(max_length=16)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Component')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='bom_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parent',
            name='eccn',
            field=models.CharField(default='ECL99', max_length=16),
        ),
        migrations.AddField(
            model_name='parent',
            name='hscomcode',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='parent',
            name='procure_method',
            field=models.CharField(choices=[('make_to_order', 'Make To Order'), ('make_to_stock', 'Make To Stock')], default='make_to_order', max_length=16),
        ),
        migrations.AddField(
            model_name='parent',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='routing_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='routing_name',
            field=models.CharField(default='B1F1S0A', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='uom_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='uom_name',
            field=models.CharField(default='PCE', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='bom_state',
            field=models.CharField(choices=[('draft', 'Awaiting X/Y Data'), ('uploaded', 'Uploaded'), ('ready', 'Ready to Upload')], default='draft', max_length=16, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('complete', 'Quoted'), ('draft', 'Not Started'), ('uploaded', 'Uploaded'), ('rfq', 'Awaiting Upload')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
        migrations.AlterField(
            model_name='suppliercomponent',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Rejected'), ('normal', 'Accepted')], default='normal', max_length=16, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='bomparent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Project'),
        ),
        migrations.AddField(
            model_name='bomcomponent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='npi.BomParent'),
        ),
        migrations.AddField(
            model_name='bomchildparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='npi.BomParent'),
        ),
        migrations.AddField(
            model_name='bomchildparent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='npi.BomParent'),
        ),
        migrations.AlterUniqueTogether(
            name='designator',
            unique_together=set([('designator', 'component')]),
        ),
    ]
