# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 07:42
from __future__ import unicode_literals

from django.db import migrations


def project_supplier_upload_date_default(apps, schema_editor):
    ProjectSupplier = apps.get_model('npi', 'ProjectSupplier')
    for supplier in ProjectSupplier.objects.all():
        if supplier.uploaded and not supplier.upload_date:
            supplier.upload_date = supplier.project.create_date
            supplier.save()


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0010_auto_20180418_1404'),
    ]

    operations = [
        migrations.RunPython(project_supplier_upload_date_default),
    ]
