# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0011_auto_20180419_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierApiDailyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('request_count', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierApiFailedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.Component')),
            ],
        ),
        migrations.AddField(
            model_name='projectsupplier',
            name='api_state',
            field=models.CharField(choices=[('inactive', ''), ('error', 'Error!'), ('finished', 'Complete'), ('ready', 'Ready'), ('pending', 'In-Progress'), ('finished_with_errors', 'Completed with Errors')], default='ready', max_length=20, verbose_name='Api State'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bom_state',
            field=models.CharField(choices=[('draft', 'Awaiting X/Y Data'), ('ready', 'Ready to Upload'), ('uploaded', 'Uploaded')], default='draft', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('draft', 'Not Started'), ('complete', 'Quoted'), ('rfq', 'Awaiting Upload'), ('uploaded', 'Uploaded')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
        migrations.AlterField(
            model_name='suppliercomponent',
            name='state',
            field=models.CharField(choices=[('normal', 'Accepted'), ('pending', 'Pending'), ('reject', 'Rejected')], default='normal', max_length=16, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='supplierapifailedsearch',
            name='project_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npi.ProjectSupplier'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierapidailyusage',
            unique_together=set([('supplier_id', 'date')]),
        ),
    ]
