# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0013_auto_20180605_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bom_state',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('draft', 'Awaiting X/Y Data'), ('ready', 'Ready to Upload')], default='draft', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('rfq', 'Awaiting Upload'), ('complete', 'Quoted'), ('uploaded', 'Uploaded'), ('draft', 'Not Started')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
        migrations.AlterField(
            model_name='projectsupplier',
            name='api_state',
            field=models.CharField(choices=[('error', 'Error!'), ('inactive', ''), ('finished', 'Complete'), ('pending', 'In-Progress'), ('finished_with_errors', 'Completed with Errors'), ('ready', 'Ready')], default='ready', max_length=20, verbose_name='Api State'),
        ),
        migrations.AlterField(
            model_name='suppliercomponent',
            name='state',
            field=models.CharField(choices=[('normal', 'Accepted'), ('pending', 'Pending'), ('reject', 'Rejected')], default='normal', max_length=16, verbose_name='State'),
        ),
    ]
