# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0015_auto_20180606_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bom_state',
            field=models.CharField(choices=[('draft', 'Awaiting X/Y Data'), ('uploaded', 'Uploaded'), ('ready', 'Ready to Upload')], default='draft', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('complete', 'Quoted'), ('draft', 'Not Started'), ('uploaded', 'Uploaded'), ('rfq', 'Awaiting Upload')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
        migrations.AlterField(
            model_name='projectsupplier',
            name='api_state',
            field=models.CharField(choices=[('pending', 'In-Progress'), ('inactive', ''), ('finished', 'Complete'), ('error', 'Error!'), ('finished_with_errors', 'Completed with Errors'), ('ready', 'Ready')], default='ready', max_length=20, verbose_name='Api State'),
        ),
        migrations.AlterField(
            model_name='suppliercomponent',
            name='state',
            field=models.CharField(choices=[('reject', 'Rejected'), ('pending', 'Pending'), ('normal', 'Accepted')], default='normal', max_length=16, verbose_name='State'),
        ),
    ]
