# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npi', '0016_auto_20180606_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bom_state',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('draft', 'Awaiting X/Y Data'), ('ready', 'Ready to Upload')], default='draft', max_length=16, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supplier_info_state',
            field=models.CharField(choices=[('rfq', 'Awaiting Upload'), ('complete', 'Quoted'), ('draft', 'Not Started'), ('uploaded', 'Uploaded')], default='draft', max_length=16, verbose_name='Supplier Information State'),
        ),
        migrations.AlterField(
            model_name='projectsupplier',
            name='api_state',
            field=models.CharField(choices=[('pending', 'In-Progress'), ('finished', 'Complete'), ('inactive', ''), ('finished_with_errors', 'Completed with Errors'), ('ready', 'Ready'), ('error', 'Error!')], default='ready', max_length=20, verbose_name='Api State'),
        ),
        migrations.AlterField(
            model_name='suppliercomponent',
            name='state',
            field=models.CharField(choices=[('reject', 'Rejected'), ('normal', 'Accepted'), ('pending', 'Pending')], default='normal', max_length=16, verbose_name='State'),
        ),
    ]
